x=raw_input("Enter any number: ")
print(type(x))

def mode1() :
    #A B C

def mode2() :
    #A C B
    print("Heading to waypoint 1")
    sleep(0.1)
    goto(coorAx, coorAz)
    #print("Yaw vehicle to ", yaw)
    #sleep(0.1)
    #set_yaw(yaw)
    print("Taking of to altitude !", altitudeA)
    sleep(0.1)
    setAltitude(altitudeA)
    print("Heading to Building")
    sleep(0.1)
    straight(detectGD)

    print("Heading to waypoint 3")
    sleep(0.1)
    goto(coorCx, coorCz)
    #print("Yaw vehicle to ", yaw)
    #sleep(0.1)
    #set_yaw(yaw)
    print("Taking of to altitude !", altitudeC)
    sleep(0.1)
    setAltitude(altitudeC)
    print("Heading to Building")
    sleep(0.1)
    straight(detectGD)

    print("Heading to waypoint 2")
    sleep(0.1)
    goto(coorBx, coorBz)
    #print("Yaw vehicle to ", yaw)
    #sleep(0.1)
    #set_yaw(yaw)
    print("Taking of to altitude!", altitudeB)
    sleep(0.1)
    setAltitude(altitudeB)
    print("Heading to Building")
    sleep(0.1)
    straight(detectGD)

    print("Yaw vehicle to ", yaw)
    sleep(0.1)
    set_yaw(yaw)
    print("Heading to ELP")
    sleep(0.1)
    goto(coorObsx, coorObsz)

def mode3() :
    #B A C
    print("Heading to waypoint 2")
    sleep(0.1)
    goto(coorBx, coorBz)
    #print("Yaw vehicle to ", yaw)
    #sleep(0.1)
    #set_yaw(yaw)
    print("Taking of to altitude!", altitudeB)
    sleep(0.1)
    setAltitude(altitudeB)
    print("Heading to Building")
    sleep(0.1)
    straight(detectGD)

    print("Heading to waypoint 1")
    sleep(0.1)
    goto(coorAx, coorAz)
    #print("Yaw vehicle to ", yaw)
    #sleep(0.1)
    #set_yaw(yaw)
    print("Taking of to altitude !", altitudeA)
    sleep(0.1)
    setAltitude(altitudeA)
    print("Heading to Building")
    sleep(0.1)
    straight(detectGD)

    print("Heading to waypoint 3")
    sleep(0.1)
    goto(coorCx, coorCz)
    #print("Yaw vehicle to ", yaw)
    #sleep(0.1)
    #set_yaw(yaw)
    print("Taking of to altitude !", altitudeC)
    sleep(0.1)
    setAltitude(altitudeC)
    print("Heading to Building")
    sleep(0.1)
    straight(detectGD)

    print("Yaw vehicle to ", yaw)
    sleep(0.1)
    set_yaw(yaw)
    print("Heading to ELP")
    sleep(0.1)
    goto(coorObsx, coorObsz)

def mode4() :
    #A B C
    print("Heading to waypoint 1")
    sleep(0.1)
    goto(coorAx, coorAz)
    #print("Yaw vehicle to ", yaw)
    #sleep(0.1)
    #set_yaw(yaw)
    print("Taking of to altitude !", altitudeA)
    sleep(0.1)
    setAltitude(altitudeA)
    print("Heading to Building")
    sleep(0.1)
    straight(detectGD)

    print("Heading to waypoint 2")
    sleep(0.1)
    goto(coorBx, coorBz)
    #print("Yaw vehicle to ", yaw)
    #sleep(0.1)
    #set_yaw(yaw)
    print("Taking of to altitude!", altitudeB)
    sleep(0.1)
    setAltitude(altitudeB)
    print("Heading to Building")
    sleep(0.1)
    straight(detectGD)

    print("Heading to waypoint 3")
    sleep(0.1)
    goto(coorCx, coorCz)
    #print("Yaw vehicle to ", yaw)
    #sleep(0.1)
    #set_yaw(yaw)
    print("Taking of to altitude !", altitudeC)
    sleep(0.1)
    setAltitude(altitudeC)
    print("Heading to Building")
    sleep(0.1)
    straight(detectGD)

    print("Yaw vehicle to ", yaw)
    sleep(0.1)
    set_yaw(yaw)
    print("Heading to ELP")
    sleep(0.1)
    goto(coorObsx, coorObsz)

def mode1() :
    #A B C
    print("Heading to waypoint 1")
    sleep(0.1)
    goto(coorAx, coorAz)
    #print("Yaw vehicle to ", yaw)
    #sleep(0.1)
    #set_yaw(yaw)
    print("Taking of to altitude !", altitudeA)
    sleep(0.1)
    setAltitude(altitudeA)
    print("Heading to Building")
    sleep(0.1)
    straight(detectGD)

    print("Heading to waypoint 2")
    sleep(0.1)
    goto(coorBx, coorBz)
    #print("Yaw vehicle to ", yaw)
    #sleep(0.1)
    #set_yaw(yaw)
    print("Taking of to altitude!", altitudeB)
    sleep(0.1)
    setAltitude(altitudeB)
    print("Heading to Building")
    sleep(0.1)
    straight(detectGD)

    print("Heading to waypoint 3")
    sleep(0.1)
    goto(coorCx, coorCz)
    #print("Yaw vehicle to ", yaw)
    #sleep(0.1)
    #set_yaw(yaw)
    print("Taking of to altitude !", altitudeC)
    sleep(0.1)
    setAltitude(altitudeC)
    print("Heading to Building")
    sleep(0.1)
    straight(detectGD)

    print("Yaw vehicle to ", yaw)
    sleep(0.1)
    set_yaw(yaw)
    print("Heading to ELP")
    sleep(0.1)
    goto(coorObsx, coorObsz)

def mode1() :
    #A B C
    print("Heading to waypoint 1")
    sleep(0.1)
    goto(coorAx, coorAz)
    #print("Yaw vehicle to ", yaw)
    #sleep(0.1)
    #set_yaw(yaw)
    print("Taking of to altitude !", altitudeA)
    sleep(0.1)
    setAltitude(altitudeA)
    print("Heading to Building")
    sleep(0.1)
    straight(detectGD)

    print("Heading to waypoint 2")
    sleep(0.1)
    goto(coorBx, coorBz)
    #print("Yaw vehicle to ", yaw)
    #sleep(0.1)
    #set_yaw(yaw)
    print("Taking of to altitude!", altitudeB)
    sleep(0.1)
    setAltitude(altitudeB)
    print("Heading to Building")
    sleep(0.1)
    straight(detectGD)

    print("Heading to waypoint 3")
    sleep(0.1)
    goto(coorCx, coorCz)
    #print("Yaw vehicle to ", yaw)
    #sleep(0.1)
    #set_yaw(yaw)
    print("Taking of to altitude !", altitudeC)
    sleep(0.1)
    setAltitude(altitudeC)
    print("Heading to Building")
    sleep(0.1)
    straight(detectGD)

    print("Yaw vehicle to ", yaw)
    sleep(0.1)
    set_yaw(yaw)
    print("Heading to ELP")
    sleep(0.1)
    goto(coorObsx, coorObsz)



while True:
    vehicle.mode = VehicleMode("LOITER")
    start()
    #sleep(0.5)
    #img = np.zeros((550, 500, 3), np.uint8)
    
    #call mode

    #mode1()
    #detectQR()

    #vals = getRealsenseInput()
    #print(vals[2])
    
    #sleep(5)

    #print("Heading to waypoint 4")
    #sleep(0.5)
    #goto(0,-40)

    #print("Heading to waypoint 5")
    #sleep(0.5)
    #goto(0,-50)
    #sleep(5)

    #print("Heading to Building")
    #sleep(0.5)
    #straight(detectGD, 0, img)
    #sleep(5)

    #goto(0,0, img)
    #sleep(5)
    #goto(-254,196, img)
    #sleep(5)
    #goto(223,232, img)
    #sleep(5)
    #goto(0,0, img)
    #sleep(10)

    #condition_yaw(yaw)
    #print("yaw to", yaw)
    #sleep(0.5)

    #print("Yaw vehicle to ", yaw)
    #sleep(0.1)
    #set_yaw(yaw)

    
    #sleep(3)

    #print("Pose vehicle to ", pose)
    #sleep(0.5)
    #set_pose(rotate, pose)
    #sleep(3)

    

    #print("Taking of to altitude 1.5!")
    #sleep(0.5)
    #setAltitude(1.5, 0, 0, img)
    #sleep(5)

    #print("Taking of to altitude 2.5!")
    #sleep(0.5)
    #setAltitude(2.5, 0, 0, img)
    #sleep(5)
    print("Mission Complete!")
    #if vehicle.channels['8']<1500 :
    #    mv.sendRemoteValue(None, None, None, None, vehicle)
    #    vehicle.mode = VehicleMode("LAND")
    #    print("landing......")
    #    sleep(5)
    #    print("Land")
    #    break
    #    sleep(5)
    break

    elif x < coorX - toleransi:
            print("Right",  x, z, "desire :", coorX, coorZ, "QR", detectedQR, "Yaw:", pose)
            mv.sendRemoteValue(None, right, None, None, vehicle)
        elif x > coorX + toleransi:
            print("left",  x, z, "desire :", coorX, coorZ, "QR", detectedQR, "Yaw:", pose)
            mv.sendRemoteValue(None, left, None, None, vehicle)
        elif z > coorZ + toleransi:
            print("forward",  x, z, "desire :", coorX, coorZ, "QR", detectedQR, "Yaw:", pose)
            mv.sendRemoteValue(forward, None, None, None, vehicle)
        elif z < coorZ - toleransi:
            print("backward",  x, z, "desire :", coorX, coorZ, "QR", detectedQR, "Yaw:", pose)
            mv.sendRemoteValue(backward, None, None, None, vehicle)
        else:
            mv.sendRemoteValue(None, None, None, None, vehicle)